[[pages]]
path = "ALARM.py"
name = "ALARM ì†Œê°œ"
icon = "â°"


[[pages]]
path = "pages/ì‹í’ˆì•Œë ˆë¥´ê¸°ì •ë³´.py"
name = "ì‹í’ˆì•Œë ˆë¥´ê¸°ë€?"
icon = "ğŸ”"

[[pages]]
name = "ALARM Menu"
icon = "ğŸ¥"
is_section = true

[[pages]]
path = "pages/01_ë ˆì‹œí”¼ì¶”ì²œ ì±—ë´‡.py"
name = "ì•ŒëŸ¬ì§€ í”„ë¦¬ ë ˆì‹œí”¼ ë§ˆë²•ì‚¬"
#icon = "ğŸ§™â€â™‚ï¸"

[[pages]]
path = "pages/02_ì„±ë¶„í‘œ ì´ë¯¸ì§€ì¸ì‹.py"
name = "ì•ŒëŸ¬ì§€ ìŠ¤ìºë„ˆ"
#icon = "ğŸ”"

[[pages]]
path = "pages/03_ëŒ€ì²´ì‹í’ˆ ì•Œë¦¬ë¯¸ë´‡.py"
name = "ì•ŒëŸ¬ì§€ ì•ˆì‹¬ ëŒ€ì²´ì‹í’ˆ ì¶”ì²œë´‡"
#icon = "ğŸ¤–"

[[pages]]
path = "pages/04_ì•Œë ˆë¥´ê¸° ì¦ìƒì •ë³´.py"
name = "ì•ŒëŸ¬ì§€ ë¦¬í¬íŠ¸"
#icon = "ğŸ“‘"